version: '3.4'
services:
  cardsconsumer:
    image: "scryfall_cards_consumer"
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=kafka1:9092
  taggedcardsconsumer:
    image: "scryfall_tagged_cards_consumer"
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=kafka1:9092