version: '3.4'
services:
  cardsconsumer:
    image: "danwiseman/scryfall-cards-consumer:latest"
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=kafka1:9092
  taggedcardsconsumer:
    image: "danwiseman/scryfall-tagged-cards-consumer:latest"
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=kafka1:9092